### ISSUE TITLE
kalendri kuvamine ei tööta teatud brauserites

### ISSUE THREAD

**Issue by marielinkepp** [rauladamson/ruhmatoo#24]
- [x] Mattias kirjutab 
- [x] ical nupp korda
- [x] uued muutuse dkoodi tagasi panna
- [x] teha kindlaks, mis kust form submitiga valesti läheb

**Comment by martinj91** [comment]
Töötasin selle kallal päris kaua, noteworthy asjad: olenevalt browseri settingutest, paistab, et safari ja firefox ei luba. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value  
Chromes ja Edges töötas mul kõik 3 funktsiooni, aga vahel pidi mitu korda proovima, et ta läbi läheks. Selle uurimiseni ma ei jõudnud. Kui keegi kes servleteid veits paremini tajub viitsib proovida tomcat11 branchis jakartaga seda tööle saada siis go for it. Quirks mode, Type: text/html (Cookie "Secure" manuaalselt trueks vahetamine ei teinud midagi).

**Comment by mattiasmoor** [comment]
Hetkel ei suudetud konkreetset viga täpselt tuvastada. Osutus otstarbekamaks, et kirjutada ümber nupu loogika. Osa funktsionaalsust võib olla seetõttu vaja hiljem uuesti tagasi lisada.
